server:
   port: 8083
   servlet:
      context-path: /training-demo
   compression:
      enabled: false
spring:
   profiles:
     active: redis
   jpa:
     properties:
       hibernate:
         dialect: org.hibernate.dialect.PostgreSQLDialect
     generate-ddl: true
     hibernate:
      ddl-auto: create
   h2:
     console:
       enabled: true
   servlet:
     multipart:
       max-file-size: 5MB
       max-request-size: 6MB
management:
  endpoints:
    web:
      exposure:
        include: health,metrics, beans,loggers,prometheus
spring-doc:
  show-actuator: true
---
spring:
  profiles: redis
  redis:
    host: localhost
    port: 6379
---
spring:
  profiles: postgress
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres